ALTER TABLE recipes ADD COLUMN IF NOT EXISTS ingredients_data JSONB DEFAULT '[]'::jsonb;
ALTER TABLE recipes ADD COLUMN IF NOT EXISTS total_calories FLOAT DEFAULT 0;
ALTER TABLE recipes ADD COLUMN IF NOT EXISTS total_protein FLOAT DEFAULT 0;
ALTER TABLE recipes ADD COLUMN IF NOT EXISTS total_carbs FLOAT DEFAULT 0;
ALTER TABLE recipes ADD COLUMN IF NOT EXISTS total_fat FLOAT DEFAULT 0;
ALTER TABLE recipes ADD COLUMN IF NOT EXISTS raw_ingredients_text TEXT;

ALTER TABLE shopping_list ADD COLUMN IF NOT EXISTS ingredient_name TEXT;
ALTER TABLE shopping_list ALTER COLUMN ingredient_id DROP NOT NULL;
